apiVersion: v2
name: alibabacloud-operators
description: A Helm chart for installing AlibabaCloud NLB, EIP and NLB Pool Operators
type: application
version: 0.2.1
appVersion: "0.2.1"
keywords:
  - alibabacloud
  - nlb
  - eip
  - operator
  - kubernetes
maintainers:
  - name: Chris Liu
    url: https://github.com/chrisliu1995
sources:
  - https://github.com/chrisliu1995/AlibabaCloud-NLB-Operator
  - https://github.com/chrisliu1995/AlibabaCloud-EIP-Operator
  - https://github.com/chrisliu1995/AlibabaCloud-NLB-Pool-Operator
