{{- if and .Values.components.nlb.enabled .Values.nlbOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nlb-operator.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nlb-operator.labels" . | nindent 4 }}
  {{- with .Values.nlbOperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
