{{- if .Values.components.nlbPool.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nlb-pool-operator.serviceAccountName" . }}-role
  labels:
    {{- include "nlb-pool-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
  - update
- apiGroups:
  - eip.alibabacloud.com
  resources:
  - eips
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - eip.alibabacloud.com
  resources:
  - eips/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlboperator.alibabacloud.com
  resources:
  - nlbs
  - servergroups
  - listeners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlboperator.alibabacloud.com
  resources:
  - nlbs/status
  - servergroups/status
  - listeners/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - nlbpools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - nlbpools/finalizers
  verbs:
  - update
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - nlbpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - portallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - portallocations/finalizers
  verbs:
  - update
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - portallocations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nlb-pool-operator.serviceAccountName" . }}-rolebinding
  labels:
    {{- include "nlb-pool-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nlb-pool-operator.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "nlb-pool-operator.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
