{{- if .Values.components.nlb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlb-operator.serviceAccountName" . }}-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nlb-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.global.alibabacloud.accessKeyId | quote }}
  access-key-secret: {{ .Values.global.alibabacloud.accessKeySecret | quote }}
  region: {{ .Values.global.alibabacloud.region | quote }}
{{- end }}
